version: "3"

services:
  view:
    build: ./src/view
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
  ai:
    build: ./src/ai
    restart: always
    ports:
      - 8001:8000
    env_file:
      - .env
