version: "3"

volumes:
  mediafiles:

services:
  view:
    build: ./src/view
    restart: always
    volumes:
      - mediafiles:/app/mediafiles
    ports:
      - 8000:8000
    env_file:
      - .env
  ai:
    build: ./src/ai
    restart: always
    volumes:
      - mediafiles:/app/mediafiles
    env_file:
      - .env
